// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/ummuys/reportify/services/report-worker/internal/dto"
)

// NewMockReportDB creates a new instance of MockReportDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportDB {
	mock := &MockReportDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReportDB is an autogenerated mock type for the ReportDB type
type MockReportDB struct {
	mock.Mock
}

type MockReportDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportDB) EXPECT() *MockReportDB_Expecter {
	return &MockReportDB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockReportDB
func (_mock *MockReportDB) Close() {
	_mock.Called()
	return
}

// MockReportDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReportDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockReportDB_Expecter) Close() *MockReportDB_Close_Call {
	return &MockReportDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockReportDB_Close_Call) Run(run func()) *MockReportDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReportDB_Close_Call) Return() *MockReportDB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReportDB_Close_Call) RunAndReturn(run func()) *MockReportDB_Close_Call {
	_c.Run(run)
	return _c
}

// GetReportInfo provides a mock function for the type MockReportDB
func (_mock *MockReportDB) GetReportInfo(ctx context.Context, in dto.GetReportInfoParams) (dto.GetReportInfoResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetReportInfo")
	}

	var r0 dto.GetReportInfoResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetReportInfoParams) (dto.GetReportInfoResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetReportInfoParams) dto.GetReportInfoResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.GetReportInfoResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GetReportInfoParams) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDB_GetReportInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReportInfo'
type MockReportDB_GetReportInfo_Call struct {
	*mock.Call
}

// GetReportInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.GetReportInfoParams
func (_e *MockReportDB_Expecter) GetReportInfo(ctx interface{}, in interface{}) *MockReportDB_GetReportInfo_Call {
	return &MockReportDB_GetReportInfo_Call{Call: _e.mock.On("GetReportInfo", ctx, in)}
}

func (_c *MockReportDB_GetReportInfo_Call) Run(run func(ctx context.Context, in dto.GetReportInfoParams)) *MockReportDB_GetReportInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GetReportInfoParams
		if args[1] != nil {
			arg1 = args[1].(dto.GetReportInfoParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportDB_GetReportInfo_Call) Return(getReportInfoResult dto.GetReportInfoResult, err error) *MockReportDB_GetReportInfo_Call {
	_c.Call.Return(getReportInfoResult, err)
	return _c
}

func (_c *MockReportDB_GetReportInfo_Call) RunAndReturn(run func(ctx context.Context, in dto.GetReportInfoParams) (dto.GetReportInfoResult, error)) *MockReportDB_GetReportInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SetReportStatus provides a mock function for the type MockReportDB
func (_mock *MockReportDB) SetReportStatus(ctx context.Context, in dto.SetReportStatusParams) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for SetReportStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.SetReportStatusParams) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReportDB_SetReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReportStatus'
type MockReportDB_SetReportStatus_Call struct {
	*mock.Call
}

// SetReportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.SetReportStatusParams
func (_e *MockReportDB_Expecter) SetReportStatus(ctx interface{}, in interface{}) *MockReportDB_SetReportStatus_Call {
	return &MockReportDB_SetReportStatus_Call{Call: _e.mock.On("SetReportStatus", ctx, in)}
}

func (_c *MockReportDB_SetReportStatus_Call) Run(run func(ctx context.Context, in dto.SetReportStatusParams)) *MockReportDB_SetReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.SetReportStatusParams
		if args[1] != nil {
			arg1 = args[1].(dto.SetReportStatusParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportDB_SetReportStatus_Call) Return(err error) *MockReportDB_SetReportStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReportDB_SetReportStatus_Call) RunAndReturn(run func(ctx context.Context, in dto.SetReportStatusParams) error) *MockReportDB_SetReportStatus_Call {
	_c.Call.Return(run)
	return _c
}
