// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReportCache is an autogenerated mock type for the ReportCache type
type MockReportCache struct {
	mock.Mock
}

type MockReportCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportCache) EXPECT() *MockReportCache_Expecter {
	return &MockReportCache_Expecter{mock: &_m.Mock}
}

// Set provides a mock function with given fields: ctx, key, value
func (_m *MockReportCache) Set(ctx context.Context, key string, value string) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockReportCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockReportCache_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockReportCache_Set_Call {
	return &MockReportCache_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockReportCache_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockReportCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockReportCache_Set_Call) Return(_a0 error) *MockReportCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportCache_Set_Call) RunAndReturn(run func(context.Context, string, string) error) *MockReportCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportCache creates a new instance of MockReportCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportCache {
	mock := &MockReportCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
