// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/ummuys/reportify/services/report-worker/internal/dto"
)

// MockReportConvert is an autogenerated mock type for the ReportConvert type
type MockReportConvert struct {
	mock.Mock
}

type MockReportConvert_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportConvert) EXPECT() *MockReportConvert_Expecter {
	return &MockReportConvert_Expecter{mock: &_m.Mock}
}

// ToCSV provides a mock function with given fields: in
func (_m *MockReportConvert) ToCSV(in dto.ConvParams) error {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for ToCSV")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.ConvParams) error); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportConvert_ToCSV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToCSV'
type MockReportConvert_ToCSV_Call struct {
	*mock.Call
}

// ToCSV is a helper method to define mock.On call
//   - in dto.ConvParams
func (_e *MockReportConvert_Expecter) ToCSV(in interface{}) *MockReportConvert_ToCSV_Call {
	return &MockReportConvert_ToCSV_Call{Call: _e.mock.On("ToCSV", in)}
}

func (_c *MockReportConvert_ToCSV_Call) Run(run func(in dto.ConvParams)) *MockReportConvert_ToCSV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.ConvParams))
	})
	return _c
}

func (_c *MockReportConvert_ToCSV_Call) Return(_a0 error) *MockReportConvert_ToCSV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportConvert_ToCSV_Call) RunAndReturn(run func(dto.ConvParams) error) *MockReportConvert_ToCSV_Call {
	_c.Call.Return(run)
	return _c
}

// ToDOCX provides a mock function with given fields: in
func (_m *MockReportConvert) ToDOCX(in dto.ConvParams) error {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for ToDOCX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.ConvParams) error); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportConvert_ToDOCX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToDOCX'
type MockReportConvert_ToDOCX_Call struct {
	*mock.Call
}

// ToDOCX is a helper method to define mock.On call
//   - in dto.ConvParams
func (_e *MockReportConvert_Expecter) ToDOCX(in interface{}) *MockReportConvert_ToDOCX_Call {
	return &MockReportConvert_ToDOCX_Call{Call: _e.mock.On("ToDOCX", in)}
}

func (_c *MockReportConvert_ToDOCX_Call) Run(run func(in dto.ConvParams)) *MockReportConvert_ToDOCX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.ConvParams))
	})
	return _c
}

func (_c *MockReportConvert_ToDOCX_Call) Return(_a0 error) *MockReportConvert_ToDOCX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportConvert_ToDOCX_Call) RunAndReturn(run func(dto.ConvParams) error) *MockReportConvert_ToDOCX_Call {
	_c.Call.Return(run)
	return _c
}

// ToJSON provides a mock function with given fields: in
func (_m *MockReportConvert) ToJSON(in dto.ConvParams) error {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for ToJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.ConvParams) error); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportConvert_ToJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToJSON'
type MockReportConvert_ToJSON_Call struct {
	*mock.Call
}

// ToJSON is a helper method to define mock.On call
//   - in dto.ConvParams
func (_e *MockReportConvert_Expecter) ToJSON(in interface{}) *MockReportConvert_ToJSON_Call {
	return &MockReportConvert_ToJSON_Call{Call: _e.mock.On("ToJSON", in)}
}

func (_c *MockReportConvert_ToJSON_Call) Run(run func(in dto.ConvParams)) *MockReportConvert_ToJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.ConvParams))
	})
	return _c
}

func (_c *MockReportConvert_ToJSON_Call) Return(_a0 error) *MockReportConvert_ToJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportConvert_ToJSON_Call) RunAndReturn(run func(dto.ConvParams) error) *MockReportConvert_ToJSON_Call {
	_c.Call.Return(run)
	return _c
}

// ToPDF provides a mock function with given fields: in
func (_m *MockReportConvert) ToPDF(in dto.ConvParams) error {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for ToPDF")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.ConvParams) error); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportConvert_ToPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToPDF'
type MockReportConvert_ToPDF_Call struct {
	*mock.Call
}

// ToPDF is a helper method to define mock.On call
//   - in dto.ConvParams
func (_e *MockReportConvert_Expecter) ToPDF(in interface{}) *MockReportConvert_ToPDF_Call {
	return &MockReportConvert_ToPDF_Call{Call: _e.mock.On("ToPDF", in)}
}

func (_c *MockReportConvert_ToPDF_Call) Run(run func(in dto.ConvParams)) *MockReportConvert_ToPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.ConvParams))
	})
	return _c
}

func (_c *MockReportConvert_ToPDF_Call) Return(_a0 error) *MockReportConvert_ToPDF_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportConvert_ToPDF_Call) RunAndReturn(run func(dto.ConvParams) error) *MockReportConvert_ToPDF_Call {
	_c.Call.Return(run)
	return _c
}

// ToXLSX provides a mock function with given fields: in
func (_m *MockReportConvert) ToXLSX(in dto.ConvParams) error {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for ToXLSX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.ConvParams) error); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportConvert_ToXLSX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToXLSX'
type MockReportConvert_ToXLSX_Call struct {
	*mock.Call
}

// ToXLSX is a helper method to define mock.On call
//   - in dto.ConvParams
func (_e *MockReportConvert_Expecter) ToXLSX(in interface{}) *MockReportConvert_ToXLSX_Call {
	return &MockReportConvert_ToXLSX_Call{Call: _e.mock.On("ToXLSX", in)}
}

func (_c *MockReportConvert_ToXLSX_Call) Run(run func(in dto.ConvParams)) *MockReportConvert_ToXLSX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.ConvParams))
	})
	return _c
}

func (_c *MockReportConvert_ToXLSX_Call) Return(_a0 error) *MockReportConvert_ToXLSX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportConvert_ToXLSX_Call) RunAndReturn(run func(dto.ConvParams) error) *MockReportConvert_ToXLSX_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportConvert creates a new instance of MockReportConvert. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportConvert(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockReportConvert {
	mock := &MockReportConvert{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
