// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/ummuys/reportify/services/report-worker/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockMinIOClient is an autogenerated mock type for the MinIOClient type
type MockMinIOClient struct {
	mock.Mock
}

type MockMinIOClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMinIOClient) EXPECT() *MockMinIOClient_Expecter {
	return &MockMinIOClient_Expecter{mock: &_m.Mock}
}

// DeleteExpiredFiles provides a mock function with given fields: ctx, in
func (_m *MockMinIOClient) DeleteExpiredFiles(ctx context.Context, in dto.DeleteExpiredFilesParams) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredFiles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.DeleteExpiredFilesParams) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMinIOClient_DeleteExpiredFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredFiles'
type MockMinIOClient_DeleteExpiredFiles_Call struct {
	*mock.Call
}

// DeleteExpiredFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.DeleteExpiredFilesParams
func (_e *MockMinIOClient_Expecter) DeleteExpiredFiles(ctx interface{}, in interface{}) *MockMinIOClient_DeleteExpiredFiles_Call {
	return &MockMinIOClient_DeleteExpiredFiles_Call{Call: _e.mock.On("DeleteExpiredFiles", ctx, in)}
}

func (_c *MockMinIOClient_DeleteExpiredFiles_Call) Run(run func(ctx context.Context, in dto.DeleteExpiredFilesParams)) *MockMinIOClient_DeleteExpiredFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.DeleteExpiredFilesParams))
	})
	return _c
}

func (_c *MockMinIOClient_DeleteExpiredFiles_Call) Return(_a0 error) *MockMinIOClient_DeleteExpiredFiles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMinIOClient_DeleteExpiredFiles_Call) RunAndReturn(run func(context.Context, dto.DeleteExpiredFilesParams) error) *MockMinIOClient_DeleteExpiredFiles_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAndPresign provides a mock function with given fields: ctx, in
func (_m *MockMinIOClient) UploadAndPresign(ctx context.Context, in dto.PutReportIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UploadAndPresign")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.PutReportIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.PutReportIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.PutReportIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMinIOClient_UploadAndPresign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAndPresign'
type MockMinIOClient_UploadAndPresign_Call struct {
	*mock.Call
}

// UploadAndPresign is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.PutReportIn
func (_e *MockMinIOClient_Expecter) UploadAndPresign(ctx interface{}, in interface{}) *MockMinIOClient_UploadAndPresign_Call {
	return &MockMinIOClient_UploadAndPresign_Call{Call: _e.mock.On("UploadAndPresign", ctx, in)}
}

func (_c *MockMinIOClient_UploadAndPresign_Call) Run(run func(ctx context.Context, in dto.PutReportIn)) *MockMinIOClient_UploadAndPresign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.PutReportIn))
	})
	return _c
}

func (_c *MockMinIOClient_UploadAndPresign_Call) Return(_a0 string, _a1 error) *MockMinIOClient_UploadAndPresign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMinIOClient_UploadAndPresign_Call) RunAndReturn(run func(context.Context, dto.PutReportIn) (string, error)) *MockMinIOClient_UploadAndPresign_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMinIOClient creates a new instance of MockMinIOClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMinIOClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMinIOClient {
	mock := &MockMinIOClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
