// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/ummuys/reportify/services/report-worker/internal/dto"
)

// MockReportDB is an autogenerated mock type for the ReportDB type
type MockReportDB struct {
	mock.Mock
}

type MockReportDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportDB) EXPECT() *MockReportDB_Expecter {
	return &MockReportDB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockReportDB) Close() {
	_m.Called()
}

// MockReportDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReportDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockReportDB_Expecter) Close() *MockReportDB_Close_Call {
	return &MockReportDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockReportDB_Close_Call) Run(run func()) *MockReportDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReportDB_Close_Call) Return() *MockReportDB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReportDB_Close_Call) RunAndReturn(run func()) *MockReportDB_Close_Call {
	_c.Run(run)
	return _c
}

// GetReportInfo provides a mock function with given fields: ctx, in
func (_m *MockReportDB) GetReportInfo(ctx context.Context, in dto.GetReportInfoParams) (dto.GetReportInfoResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetReportInfo")
	}

	var r0 dto.GetReportInfoResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetReportInfoParams) (dto.GetReportInfoResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetReportInfoParams) dto.GetReportInfoResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.GetReportInfoResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.GetReportInfoParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportDB_GetReportInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReportInfo'
type MockReportDB_GetReportInfo_Call struct {
	*mock.Call
}

// GetReportInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.GetReportInfoParams
func (_e *MockReportDB_Expecter) GetReportInfo(ctx interface{}, in interface{}) *MockReportDB_GetReportInfo_Call {
	return &MockReportDB_GetReportInfo_Call{Call: _e.mock.On("GetReportInfo", ctx, in)}
}

func (_c *MockReportDB_GetReportInfo_Call) Run(run func(ctx context.Context, in dto.GetReportInfoParams)) *MockReportDB_GetReportInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.GetReportInfoParams))
	})
	return _c
}

func (_c *MockReportDB_GetReportInfo_Call) Return(_a0 dto.GetReportInfoResult, _a1 error) *MockReportDB_GetReportInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportDB_GetReportInfo_Call) RunAndReturn(run func(context.Context, dto.GetReportInfoParams) (dto.GetReportInfoResult, error)) *MockReportDB_GetReportInfo_Call {
	_c.Call.Return(run)
	return _c
}

// MarkArchived provides a mock function with given fields: ctx, in
func (_m *MockReportDB) MarkArchived(ctx context.Context, in dto.MarkArchivedParams) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for MarkArchived")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.MarkArchivedParams) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportDB_MarkArchived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkArchived'
type MockReportDB_MarkArchived_Call struct {
	*mock.Call
}

// MarkArchived is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.MarkArchivedParams
func (_e *MockReportDB_Expecter) MarkArchived(ctx interface{}, in interface{}) *MockReportDB_MarkArchived_Call {
	return &MockReportDB_MarkArchived_Call{Call: _e.mock.On("MarkArchived", ctx, in)}
}

func (_c *MockReportDB_MarkArchived_Call) Run(run func(ctx context.Context, in dto.MarkArchivedParams)) *MockReportDB_MarkArchived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.MarkArchivedParams))
	})
	return _c
}

func (_c *MockReportDB_MarkArchived_Call) Return(_a0 error) *MockReportDB_MarkArchived_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportDB_MarkArchived_Call) RunAndReturn(run func(context.Context, dto.MarkArchivedParams) error) *MockReportDB_MarkArchived_Call {
	_c.Call.Return(run)
	return _c
}

// PickAndMarkArchiving provides a mock function with given fields: ctx, in
func (_m *MockReportDB) PickAndMarkArchiving(ctx context.Context, in dto.PickAndMarkArchivingParams) (dto.PickAndMarkArchivingResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PickAndMarkArchiving")
	}

	var r0 dto.PickAndMarkArchivingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.PickAndMarkArchivingParams) (dto.PickAndMarkArchivingResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.PickAndMarkArchivingParams) dto.PickAndMarkArchivingResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.PickAndMarkArchivingResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.PickAndMarkArchivingParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportDB_PickAndMarkArchiving_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PickAndMarkArchiving'
type MockReportDB_PickAndMarkArchiving_Call struct {
	*mock.Call
}

// PickAndMarkArchiving is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.PickAndMarkArchivingParams
func (_e *MockReportDB_Expecter) PickAndMarkArchiving(ctx interface{}, in interface{}) *MockReportDB_PickAndMarkArchiving_Call {
	return &MockReportDB_PickAndMarkArchiving_Call{Call: _e.mock.On("PickAndMarkArchiving", ctx, in)}
}

func (_c *MockReportDB_PickAndMarkArchiving_Call) Run(run func(ctx context.Context, in dto.PickAndMarkArchivingParams)) *MockReportDB_PickAndMarkArchiving_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.PickAndMarkArchivingParams))
	})
	return _c
}

func (_c *MockReportDB_PickAndMarkArchiving_Call) Return(_a0 dto.PickAndMarkArchivingResult, _a1 error) *MockReportDB_PickAndMarkArchiving_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportDB_PickAndMarkArchiving_Call) RunAndReturn(run func(context.Context, dto.PickAndMarkArchivingParams) (dto.PickAndMarkArchivingResult, error)) *MockReportDB_PickAndMarkArchiving_Call {
	_c.Call.Return(run)
	return _c
}

// SetReportStatus provides a mock function with given fields: ctx, in
func (_m *MockReportDB) SetReportStatus(ctx context.Context, in dto.SetReportStatusParams) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for SetReportStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SetReportStatusParams) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportDB_SetReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReportStatus'
type MockReportDB_SetReportStatus_Call struct {
	*mock.Call
}

// SetReportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.SetReportStatusParams
func (_e *MockReportDB_Expecter) SetReportStatus(ctx interface{}, in interface{}) *MockReportDB_SetReportStatus_Call {
	return &MockReportDB_SetReportStatus_Call{Call: _e.mock.On("SetReportStatus", ctx, in)}
}

func (_c *MockReportDB_SetReportStatus_Call) Run(run func(ctx context.Context, in dto.SetReportStatusParams)) *MockReportDB_SetReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.SetReportStatusParams))
	})
	return _c
}

func (_c *MockReportDB_SetReportStatus_Call) Return(_a0 error) *MockReportDB_SetReportStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportDB_SetReportStatus_Call) RunAndReturn(run func(context.Context, dto.SetReportStatusParams) error) *MockReportDB_SetReportStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportDB creates a new instance of MockReportDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportDB {
	mock := &MockReportDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
