// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/ummuys/reportify/services/report-worker/internal/dto"
)

// NewMockDatasourceDB creates a new instance of MockDatasourceDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatasourceDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatasourceDB {
	mock := &MockDatasourceDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatasourceDB is an autogenerated mock type for the DatasourceDB type
type MockDatasourceDB struct {
	mock.Mock
}

type MockDatasourceDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatasourceDB) EXPECT() *MockDatasourceDB_Expecter {
	return &MockDatasourceDB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDatasourceDB
func (_mock *MockDatasourceDB) Close() {
	_mock.Called()
	return
}

// MockDatasourceDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDatasourceDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDatasourceDB_Expecter) Close() *MockDatasourceDB_Close_Call {
	return &MockDatasourceDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDatasourceDB_Close_Call) Run(run func()) *MockDatasourceDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatasourceDB_Close_Call) Return() *MockDatasourceDB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDatasourceDB_Close_Call) RunAndReturn(run func()) *MockDatasourceDB_Close_Call {
	_c.Run(run)
	return _c
}

// GetData provides a mock function for the type MockDatasourceDB
func (_mock *MockDatasourceDB) GetData(ctx context.Context, in dto.GetDataParams) (dto.GetDataResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 dto.GetDataResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetDataParams) (dto.GetDataResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetDataParams) dto.GetDataResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.GetDataResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GetDataParams) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasourceDB_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type MockDatasourceDB_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.GetDataParams
func (_e *MockDatasourceDB_Expecter) GetData(ctx interface{}, in interface{}) *MockDatasourceDB_GetData_Call {
	return &MockDatasourceDB_GetData_Call{Call: _e.mock.On("GetData", ctx, in)}
}

func (_c *MockDatasourceDB_GetData_Call) Run(run func(ctx context.Context, in dto.GetDataParams)) *MockDatasourceDB_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GetDataParams
		if args[1] != nil {
			arg1 = args[1].(dto.GetDataParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatasourceDB_GetData_Call) Return(getDataResult dto.GetDataResult, err error) *MockDatasourceDB_GetData_Call {
	_c.Call.Return(getDataResult, err)
	return _c
}

func (_c *MockDatasourceDB_GetData_Call) RunAndReturn(run func(ctx context.Context, in dto.GetDataParams) (dto.GetDataResult, error)) *MockDatasourceDB_GetData_Call {
	_c.Call.Return(run)
	return _c
}
