// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/ummuys/reportify/services/report-worker/internal/dto"
)

// NewMockMinIOClient creates a new instance of MockMinIOClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMinIOClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMinIOClient {
	mock := &MockMinIOClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMinIOClient is an autogenerated mock type for the MinIOClient type
type MockMinIOClient struct {
	mock.Mock
}

type MockMinIOClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMinIOClient) EXPECT() *MockMinIOClient_Expecter {
	return &MockMinIOClient_Expecter{mock: &_m.Mock}
}

// UploadAndPresign provides a mock function for the type MockMinIOClient
func (_mock *MockMinIOClient) UploadAndPresign(ctx context.Context, in dto.PutReportIn) (string, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UploadAndPresign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.PutReportIn) (string, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.PutReportIn) string); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.PutReportIn) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMinIOClient_UploadAndPresign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAndPresign'
type MockMinIOClient_UploadAndPresign_Call struct {
	*mock.Call
}

// UploadAndPresign is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.PutReportIn
func (_e *MockMinIOClient_Expecter) UploadAndPresign(ctx interface{}, in interface{}) *MockMinIOClient_UploadAndPresign_Call {
	return &MockMinIOClient_UploadAndPresign_Call{Call: _e.mock.On("UploadAndPresign", ctx, in)}
}

func (_c *MockMinIOClient_UploadAndPresign_Call) Run(run func(ctx context.Context, in dto.PutReportIn)) *MockMinIOClient_UploadAndPresign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.PutReportIn
		if args[1] != nil {
			arg1 = args[1].(dto.PutReportIn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMinIOClient_UploadAndPresign_Call) Return(s string, err error) *MockMinIOClient_UploadAndPresign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMinIOClient_UploadAndPresign_Call) RunAndReturn(run func(ctx context.Context, in dto.PutReportIn) (string, error)) *MockMinIOClient_UploadAndPresign_Call {
	_c.Call.Return(run)
	return _c
}
