// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKafkaConsumer creates a new instance of MockKafkaConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaConsumer {
	mock := &MockKafkaConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKafkaConsumer is an autogenerated mock type for the KafkaConsumer type
type MockKafkaConsumer struct {
	mock.Mock
}

type MockKafkaConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKafkaConsumer) EXPECT() *MockKafkaConsumer_Expecter {
	return &MockKafkaConsumer_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockKafkaConsumer
func (_mock *MockKafkaConsumer) Run(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKafkaConsumer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockKafkaConsumer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKafkaConsumer_Expecter) Run(ctx interface{}) *MockKafkaConsumer_Run_Call {
	return &MockKafkaConsumer_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockKafkaConsumer_Run_Call) Run(run func(ctx context.Context)) *MockKafkaConsumer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKafkaConsumer_Run_Call) Return(err error) *MockKafkaConsumer_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKafkaConsumer_Run_Call) RunAndReturn(run func(ctx context.Context) error) *MockKafkaConsumer_Run_Call {
	_c.Call.Return(run)
	return _c
}
