version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - bodyclose
    - gosec

issues:
  exclude-use-default: false
