// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: report/service/v1/report_service.proto

package reportservicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comm          string                 `protobuf:"bytes,3,opt,name=comm,proto3" json:"comm,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	CsvSep        string                 `protobuf:"bytes,6,opt,name=csv_sep,json=csvSep,proto3" json:"csv_sep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReportRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateReportRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateReportRequest) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *CreateReportRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CreateReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CreateReportRequest) GetCsvSep() string {
	if x != nil {
		return x.CsvSep
	}
	return ""
}

type CreateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportResponse) Reset() {
	*x = CreateReportResponse{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportResponse) ProtoMessage() {}

func (x *CreateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportResponse.ProtoReflect.Descriptor instead.
func (*CreateReportResponse) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *CreateReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReportStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReportStatusRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *ReportStatusRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type ReportStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReportStatusResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReportStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListUserReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReportsRequest) Reset() {
	*x = ListUserReportsRequest{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReportsRequest) ProtoMessage() {}

func (x *ListUserReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReportsRequest.ProtoReflect.Descriptor instead.
func (*ListUserReportsRequest) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserReportsRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type ListUserReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*ReportMetadata      `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReportsResponse) Reset() {
	*x = ListUserReportsResponse{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReportsResponse) ProtoMessage() {}

func (x *ListUserReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReportsResponse.ProtoReflect.Descriptor instead.
func (*ListUserReportsResponse) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserReportsResponse) GetReports() []*ReportMetadata {
	if x != nil {
		return x.Reports
	}
	return nil
}

type ReportInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInfoRequest) Reset() {
	*x = ReportInfoRequest{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInfoRequest) ProtoMessage() {}

func (x *ReportInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInfoRequest.ProtoReflect.Descriptor instead.
func (*ReportInfoRequest) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReportInfoRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *ReportInfoRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type ReportInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *ReportMetadata        `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInfoResponse) Reset() {
	*x = ReportInfoResponse{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInfoResponse) ProtoMessage() {}

func (x *ReportInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInfoResponse.ProtoReflect.Descriptor instead.
func (*ReportInfoResponse) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReportInfoResponse) GetReport() *ReportMetadata {
	if x != nil {
		return x.Report
	}
	return nil
}

type DeleteUserReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReportsRequest) Reset() {
	*x = DeleteUserReportsRequest{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReportsRequest) ProtoMessage() {}

func (x *DeleteUserReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReportsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserReportsRequest) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserReportsRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type DeleteUserReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	ReportId      string                 `protobuf:"bytes,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReportRequest) Reset() {
	*x = DeleteUserReportRequest{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReportRequest) ProtoMessage() {}

func (x *DeleteUserReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReportRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserReportRequest) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserReportRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *DeleteUserReportRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type DeleteUserReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReportResponse) Reset() {
	*x = DeleteUserReportResponse{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReportResponse) ProtoMessage() {}

func (x *DeleteUserReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReportResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserReportResponse) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type ReportMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comm          string                 `protobuf:"bytes,3,opt,name=comm,proto3" json:"comm,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	CsvSep        string                 `protobuf:"bytes,6,opt,name=csv_sep,json=csvSep,proto3" json:"csv_sep,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	FilePath      string                 `protobuf:"bytes,8,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,10,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMetadata) Reset() {
	*x = ReportMetadata{}
	mi := &file_report_service_v1_report_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMetadata) ProtoMessage() {}

func (x *ReportMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_report_service_v1_report_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMetadata.ProtoReflect.Descriptor instead.
func (*ReportMetadata) Descriptor() ([]byte, []int) {
	return file_report_service_v1_report_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReportMetadata) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReportMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportMetadata) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ReportMetadata) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ReportMetadata) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ReportMetadata) GetCsvSep() string {
	if x != nil {
		return x.CsvSep
	}
	return ""
}

func (x *ReportMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportMetadata) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ReportMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReportMetadata) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_report_service_v1_report_service_proto protoreflect.FileDescriptor

const file_report_service_v1_report_service_proto_rawDesc = "" +
	"\n" +
	"&report/service/v1/report_service.proto\x12\x11report.service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa1\x01\n" +
	"\x13CreateReportRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04comm\x18\x03 \x01(\tR\x04comm\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x17\n" +
	"\acsv_sep\x18\x06 \x01(\tR\x06csvSep\"K\n" +
	"\x14CreateReportResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"O\n" +
	"\x13ReportStatusRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"K\n" +
	"\x14ReportStatusResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\x16ListUserReportsRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\"V\n" +
	"\x17ListUserReportsResponse\x12;\n" +
	"\areports\x18\x01 \x03(\v2!.report.service.v1.ReportMetadataR\areports\"M\n" +
	"\x11ReportInfoRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"O\n" +
	"\x12ReportInfoResponse\x129\n" +
	"\x06report\x18\x01 \x01(\v2!.report.service.v1.ReportMetadataR\x06report\"7\n" +
	"\x18DeleteUserReportsRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\"S\n" +
	"\x17DeleteUserReportRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\tR\breportId\"7\n" +
	"\x18DeleteUserReportResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"\xa5\x02\n" +
	"\x0eReportMetadata\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04comm\x18\x03 \x01(\tR\x04comm\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x17\n" +
	"\acsv_sep\x18\x06 \x01(\tR\x06csvSep\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1b\n" +
	"\tfile_path\x18\b \x01(\tR\bfilePath\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\aerr_msg\x18\n" +
	" \x01(\tR\x06errMsg2\xdd\x04\n" +
	"\rReportService\x12_\n" +
	"\fCreateReport\x12&.report.service.v1.CreateReportRequest\x1a'.report.service.v1.CreateReportResponse\x12_\n" +
	"\fReportStatus\x12&.report.service.v1.ReportStatusRequest\x1a'.report.service.v1.ReportStatusResponse\x12h\n" +
	"\x0fListUserReports\x12).report.service.v1.ListUserReportsRequest\x1a*.report.service.v1.ListUserReportsResponse\x12Y\n" +
	"\n" +
	"ReportInfo\x12$.report.service.v1.ReportInfoRequest\x1a%.report.service.v1.ReportInfoResponse\x12X\n" +
	"\x11DeleteUserReports\x12+.report.service.v1.DeleteUserReportsRequest\x1a\x16.google.protobuf.Empty\x12k\n" +
	"\x10DeleteUserReport\x12*.report.service.v1.DeleteUserReportRequest\x1a+.report.service.v1.DeleteUserReportResponseBFZDgithub.com/ummuys/reportify/api/pb/report/service/v1;reportservicev1b\x06proto3"

var (
	file_report_service_v1_report_service_proto_rawDescOnce sync.Once
	file_report_service_v1_report_service_proto_rawDescData []byte
)

func file_report_service_v1_report_service_proto_rawDescGZIP() []byte {
	file_report_service_v1_report_service_proto_rawDescOnce.Do(func() {
		file_report_service_v1_report_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_service_v1_report_service_proto_rawDesc), len(file_report_service_v1_report_service_proto_rawDesc)))
	})
	return file_report_service_v1_report_service_proto_rawDescData
}

var file_report_service_v1_report_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_report_service_v1_report_service_proto_goTypes = []any{
	(*CreateReportRequest)(nil),      // 0: report.service.v1.CreateReportRequest
	(*CreateReportResponse)(nil),     // 1: report.service.v1.CreateReportResponse
	(*ReportStatusRequest)(nil),      // 2: report.service.v1.ReportStatusRequest
	(*ReportStatusResponse)(nil),     // 3: report.service.v1.ReportStatusResponse
	(*ListUserReportsRequest)(nil),   // 4: report.service.v1.ListUserReportsRequest
	(*ListUserReportsResponse)(nil),  // 5: report.service.v1.ListUserReportsResponse
	(*ReportInfoRequest)(nil),        // 6: report.service.v1.ReportInfoRequest
	(*ReportInfoResponse)(nil),       // 7: report.service.v1.ReportInfoResponse
	(*DeleteUserReportsRequest)(nil), // 8: report.service.v1.DeleteUserReportsRequest
	(*DeleteUserReportRequest)(nil),  // 9: report.service.v1.DeleteUserReportRequest
	(*DeleteUserReportResponse)(nil), // 10: report.service.v1.DeleteUserReportResponse
	(*ReportMetadata)(nil),           // 11: report.service.v1.ReportMetadata
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 13: google.protobuf.Empty
}
var file_report_service_v1_report_service_proto_depIdxs = []int32{
	11, // 0: report.service.v1.ListUserReportsResponse.reports:type_name -> report.service.v1.ReportMetadata
	11, // 1: report.service.v1.ReportInfoResponse.report:type_name -> report.service.v1.ReportMetadata
	12, // 2: report.service.v1.ReportMetadata.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: report.service.v1.ReportService.CreateReport:input_type -> report.service.v1.CreateReportRequest
	2,  // 4: report.service.v1.ReportService.ReportStatus:input_type -> report.service.v1.ReportStatusRequest
	4,  // 5: report.service.v1.ReportService.ListUserReports:input_type -> report.service.v1.ListUserReportsRequest
	6,  // 6: report.service.v1.ReportService.ReportInfo:input_type -> report.service.v1.ReportInfoRequest
	8,  // 7: report.service.v1.ReportService.DeleteUserReports:input_type -> report.service.v1.DeleteUserReportsRequest
	9,  // 8: report.service.v1.ReportService.DeleteUserReport:input_type -> report.service.v1.DeleteUserReportRequest
	1,  // 9: report.service.v1.ReportService.CreateReport:output_type -> report.service.v1.CreateReportResponse
	3,  // 10: report.service.v1.ReportService.ReportStatus:output_type -> report.service.v1.ReportStatusResponse
	5,  // 11: report.service.v1.ReportService.ListUserReports:output_type -> report.service.v1.ListUserReportsResponse
	7,  // 12: report.service.v1.ReportService.ReportInfo:output_type -> report.service.v1.ReportInfoResponse
	13, // 13: report.service.v1.ReportService.DeleteUserReports:output_type -> google.protobuf.Empty
	10, // 14: report.service.v1.ReportService.DeleteUserReport:output_type -> report.service.v1.DeleteUserReportResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_report_service_v1_report_service_proto_init() }
func file_report_service_v1_report_service_proto_init() {
	if File_report_service_v1_report_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_service_v1_report_service_proto_rawDesc), len(file_report_service_v1_report_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_service_v1_report_service_proto_goTypes,
		DependencyIndexes: file_report_service_v1_report_service_proto_depIdxs,
		MessageInfos:      file_report_service_v1_report_service_proto_msgTypes,
	}.Build()
	File_report_service_v1_report_service_proto = out.File
	file_report_service_v1_report_service_proto_goTypes = nil
	file_report_service_v1_report_service_proto_depIdxs = nil
}
