// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: datasource/service/v1/datasource_service.proto

package datasourceservicev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasRequest) Reset() {
	*x = ListSchemasRequest{}
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasRequest) ProtoMessage() {}

func (x *ListSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListSchemasRequest) Descriptor() ([]byte, []int) {
	return file_datasource_service_v1_datasource_service_proto_rawDescGZIP(), []int{0}
}

type ListSchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*Schema              `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_datasource_service_v1_datasource_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListSchemasResponse) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaName    string                 `protobuf:"bytes,1,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	SchemaComm    string                 `protobuf:"bytes,2,opt,name=schema_comm,json=schemaComm,proto3" json:"schema_comm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_datasource_service_v1_datasource_service_proto_rawDescGZIP(), []int{2}
}

func (x *Schema) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *Schema) GetSchemaComm() string {
	if x != nil {
		return x.SchemaComm
	}
	return ""
}

type ListTablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaName    string                 `protobuf:"bytes,1,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTablesRequest) Reset() {
	*x = ListTablesRequest{}
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesRequest) ProtoMessage() {}

func (x *ListTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesRequest.ProtoReflect.Descriptor instead.
func (*ListTablesRequest) Descriptor() ([]byte, []int) {
	return file_datasource_service_v1_datasource_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListTablesRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

type ListTablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*Table               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTablesResponse) Reset() {
	*x = ListTablesResponse{}
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesResponse) ProtoMessage() {}

func (x *ListTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesResponse.ProtoReflect.Descriptor instead.
func (*ListTablesResponse) Descriptor() ([]byte, []int) {
	return file_datasource_service_v1_datasource_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListTablesResponse) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	TableComm     string                 `protobuf:"bytes,2,opt,name=table_comm,json=tableComm,proto3" json:"table_comm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_datasource_service_v1_datasource_service_proto_rawDescGZIP(), []int{5}
}

func (x *Table) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Table) GetTableComm() string {
	if x != nil {
		return x.TableComm
	}
	return ""
}

type ListColumnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaName    string                 `protobuf:"bytes,1,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	TableName     string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListColumnsRequest) Reset() {
	*x = ListColumnsRequest{}
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListColumnsRequest) ProtoMessage() {}

func (x *ListColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListColumnsRequest.ProtoReflect.Descriptor instead.
func (*ListColumnsRequest) Descriptor() ([]byte, []int) {
	return file_datasource_service_v1_datasource_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListColumnsRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *ListColumnsRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type ListColumnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*Column              `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListColumnsResponse) Reset() {
	*x = ListColumnsResponse{}
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListColumnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListColumnsResponse) ProtoMessage() {}

func (x *ListColumnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListColumnsResponse.ProtoReflect.Descriptor instead.
func (*ListColumnsResponse) Descriptor() ([]byte, []int) {
	return file_datasource_service_v1_datasource_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListColumnsResponse) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnName    string                 `protobuf:"bytes,1,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	ColumnComm    string                 `protobuf:"bytes,2,opt,name=column_comm,json=columnComm,proto3" json:"column_comm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_service_v1_datasource_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_datasource_service_v1_datasource_service_proto_rawDescGZIP(), []int{8}
}

func (x *Column) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *Column) GetColumnComm() string {
	if x != nil {
		return x.ColumnComm
	}
	return ""
}

var File_datasource_service_v1_datasource_service_proto protoreflect.FileDescriptor

const file_datasource_service_v1_datasource_service_proto_rawDesc = "" +
	"\n" +
	".datasource/service/v1/datasource_service.proto\x12\x15datasource.service.v1\"\x14\n" +
	"\x12ListSchemasRequest\"N\n" +
	"\x13ListSchemasResponse\x127\n" +
	"\aschemas\x18\x01 \x03(\v2\x1d.datasource.service.v1.SchemaR\aschemas\"J\n" +
	"\x06Schema\x12\x1f\n" +
	"\vschema_name\x18\x01 \x01(\tR\n" +
	"schemaName\x12\x1f\n" +
	"\vschema_comm\x18\x02 \x01(\tR\n" +
	"schemaComm\"4\n" +
	"\x11ListTablesRequest\x12\x1f\n" +
	"\vschema_name\x18\x01 \x01(\tR\n" +
	"schemaName\"J\n" +
	"\x12ListTablesResponse\x124\n" +
	"\x06tables\x18\x01 \x03(\v2\x1c.datasource.service.v1.TableR\x06tables\"E\n" +
	"\x05Table\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1d\n" +
	"\n" +
	"table_comm\x18\x02 \x01(\tR\ttableComm\"T\n" +
	"\x12ListColumnsRequest\x12\x1f\n" +
	"\vschema_name\x18\x01 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\"N\n" +
	"\x13ListColumnsResponse\x127\n" +
	"\acolumns\x18\x01 \x03(\v2\x1d.datasource.service.v1.ColumnR\acolumns\"J\n" +
	"\x06Column\x12\x1f\n" +
	"\vcolumn_name\x18\x01 \x01(\tR\n" +
	"columnName\x12\x1f\n" +
	"\vcolumn_comm\x18\x02 \x01(\tR\n" +
	"columnComm2\xc2\x02\n" +
	"\x11DatasourceService\x12d\n" +
	"\vListSchemas\x12).datasource.service.v1.ListSchemasRequest\x1a*.datasource.service.v1.ListSchemasResponse\x12a\n" +
	"\n" +
	"ListTables\x12(.datasource.service.v1.ListTablesRequest\x1a).datasource.service.v1.ListTablesResponse\x12d\n" +
	"\vListColumns\x12).datasource.service.v1.ListColumnsRequest\x1a*.datasource.service.v1.ListColumnsResponseBNZLgithub.com/ummuys/reportify/api/pb/datasource/service/v1;datasourceservicev1b\x06proto3"

var (
	file_datasource_service_v1_datasource_service_proto_rawDescOnce sync.Once
	file_datasource_service_v1_datasource_service_proto_rawDescData []byte
)

func file_datasource_service_v1_datasource_service_proto_rawDescGZIP() []byte {
	file_datasource_service_v1_datasource_service_proto_rawDescOnce.Do(func() {
		file_datasource_service_v1_datasource_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datasource_service_v1_datasource_service_proto_rawDesc), len(file_datasource_service_v1_datasource_service_proto_rawDesc)))
	})
	return file_datasource_service_v1_datasource_service_proto_rawDescData
}

var (
	file_datasource_service_v1_datasource_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
	file_datasource_service_v1_datasource_service_proto_goTypes  = []any{
		(*ListSchemasRequest)(nil),  // 0: datasource.service.v1.ListSchemasRequest
		(*ListSchemasResponse)(nil), // 1: datasource.service.v1.ListSchemasResponse
		(*Schema)(nil),              // 2: datasource.service.v1.Schema
		(*ListTablesRequest)(nil),   // 3: datasource.service.v1.ListTablesRequest
		(*ListTablesResponse)(nil),  // 4: datasource.service.v1.ListTablesResponse
		(*Table)(nil),               // 5: datasource.service.v1.Table
		(*ListColumnsRequest)(nil),  // 6: datasource.service.v1.ListColumnsRequest
		(*ListColumnsResponse)(nil), // 7: datasource.service.v1.ListColumnsResponse
		(*Column)(nil),              // 8: datasource.service.v1.Column
	}
)
var file_datasource_service_v1_datasource_service_proto_depIdxs = []int32{
	2, // 0: datasource.service.v1.ListSchemasResponse.schemas:type_name -> datasource.service.v1.Schema
	5, // 1: datasource.service.v1.ListTablesResponse.tables:type_name -> datasource.service.v1.Table
	8, // 2: datasource.service.v1.ListColumnsResponse.columns:type_name -> datasource.service.v1.Column
	0, // 3: datasource.service.v1.DatasourceService.ListSchemas:input_type -> datasource.service.v1.ListSchemasRequest
	3, // 4: datasource.service.v1.DatasourceService.ListTables:input_type -> datasource.service.v1.ListTablesRequest
	6, // 5: datasource.service.v1.DatasourceService.ListColumns:input_type -> datasource.service.v1.ListColumnsRequest
	1, // 6: datasource.service.v1.DatasourceService.ListSchemas:output_type -> datasource.service.v1.ListSchemasResponse
	4, // 7: datasource.service.v1.DatasourceService.ListTables:output_type -> datasource.service.v1.ListTablesResponse
	7, // 8: datasource.service.v1.DatasourceService.ListColumns:output_type -> datasource.service.v1.ListColumnsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_datasource_service_v1_datasource_service_proto_init() }
func file_datasource_service_v1_datasource_service_proto_init() {
	if File_datasource_service_v1_datasource_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datasource_service_v1_datasource_service_proto_rawDesc), len(file_datasource_service_v1_datasource_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datasource_service_v1_datasource_service_proto_goTypes,
		DependencyIndexes: file_datasource_service_v1_datasource_service_proto_depIdxs,
		MessageInfos:      file_datasource_service_v1_datasource_service_proto_msgTypes,
	}.Build()
	File_datasource_service_v1_datasource_service_proto = out.File
	file_datasource_service_v1_datasource_service_proto_goTypes = nil
	file_datasource_service_v1_datasource_service_proto_depIdxs = nil
}
