// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: datasource/service/v1/datasource_service.proto

package datasourceservicev1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatasourceService_ListSchemas_FullMethodName = "/datasource.service.v1.DatasourceService/ListSchemas"
	DatasourceService_ListTables_FullMethodName  = "/datasource.service.v1.DatasourceService/ListTables"
	DatasourceService_ListColumns_FullMethodName = "/datasource.service.v1.DatasourceService/ListColumns"
)

// DatasourceServiceClient is the client API for DatasourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatasourceServiceClient interface {
	ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error)
	ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
	ListColumns(ctx context.Context, in *ListColumnsRequest, opts ...grpc.CallOption) (*ListColumnsResponse, error)
}

type datasourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatasourceServiceClient(cc grpc.ClientConnInterface) DatasourceServiceClient {
	return &datasourceServiceClient{cc}
}

func (c *datasourceServiceClient) ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemasResponse)
	err := c.cc.Invoke(ctx, DatasourceService_ListSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasourceServiceClient) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTablesResponse)
	err := c.cc.Invoke(ctx, DatasourceService_ListTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datasourceServiceClient) ListColumns(ctx context.Context, in *ListColumnsRequest, opts ...grpc.CallOption) (*ListColumnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListColumnsResponse)
	err := c.cc.Invoke(ctx, DatasourceService_ListColumns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatasourceServiceServer is the server API for DatasourceService service.
// All implementations must embed UnimplementedDatasourceServiceServer
// for forward compatibility.
type DatasourceServiceServer interface {
	ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
	ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error)
	ListColumns(context.Context, *ListColumnsRequest) (*ListColumnsResponse, error)
	mustEmbedUnimplementedDatasourceServiceServer()
}

// UnimplementedDatasourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatasourceServiceServer struct{}

func (UnimplementedDatasourceServiceServer) ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchemas not implemented")
}

func (UnimplementedDatasourceServiceServer) ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTables not implemented")
}

func (UnimplementedDatasourceServiceServer) ListColumns(context.Context, *ListColumnsRequest) (*ListColumnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListColumns not implemented")
}
func (UnimplementedDatasourceServiceServer) mustEmbedUnimplementedDatasourceServiceServer() {}
func (UnimplementedDatasourceServiceServer) testEmbeddedByValue()                           {}

// UnsafeDatasourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatasourceServiceServer will
// result in compilation errors.
type UnsafeDatasourceServiceServer interface {
	mustEmbedUnimplementedDatasourceServiceServer()
}

func RegisterDatasourceServiceServer(s grpc.ServiceRegistrar, srv DatasourceServiceServer) {
	// If the following call panics, it indicates UnimplementedDatasourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatasourceService_ServiceDesc, srv)
}

func _DatasourceService_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasourceServiceServer).ListSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasourceService_ListSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasourceServiceServer).ListSchemas(ctx, req.(*ListSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasourceService_ListTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasourceServiceServer).ListTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasourceService_ListTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasourceServiceServer).ListTables(ctx, req.(*ListTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatasourceService_ListColumns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListColumnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatasourceServiceServer).ListColumns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatasourceService_ListColumns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatasourceServiceServer).ListColumns(ctx, req.(*ListColumnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatasourceService_ServiceDesc is the grpc.ServiceDesc for DatasourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatasourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datasource.service.v1.DatasourceService",
	HandlerType: (*DatasourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSchemas",
			Handler:    _DatasourceService_ListSchemas_Handler,
		},
		{
			MethodName: "ListTables",
			Handler:    _DatasourceService_ListTables_Handler,
		},
		{
			MethodName: "ListColumns",
			Handler:    _DatasourceService_ListColumns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datasource/service/v1/datasource_service.proto",
}
