services:


  auth-service:
    build: 
      context: ../
      dockerfile: deployment/Dockerfile
    image: auth-service
    container_name: ${AUTH_SERVICE_CONTAINER_NAME}
    env_file:
      - ./../.env
      - ./../services/auth/.env
    ports:
      - ${AUTH_SERVICE_OUT_PORT}:${AUTH_SERVICE_IN_PORT}
    depends_on:
      auth-migration:
        condition: service_completed_successfully
    networks:
      - reportify_network
    
    
  auth-db:
    image: postgres:17
    env_file:
      - ./../.env
    container_name: ${AUTH_DB_CONTAINER_NAME}
    environment: 
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - ${AUTH_DB_OUT_PORT}:${AUTH_DB_IN_PORT}
    networks:
      - reportify_network
    volumes:
      - pg_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}" ]
      interval: 2s
      timeout: 2s
      retries: 10
    restart: unless-stopped

  auth-migration:
    image: migrate/migrate
    env_file:
      - ./../.env
    container_name: auth-migration
    environment:
      AUTH_DB_MIG: ${AUTH_DB_MIG}
    volumes:
      - ./assets/db/userdata/migrations:/migrations
    command: ["-path", "/migrations", "-database", "${AUTH_DB_MIG}", "up"]
    depends_on:
      auth-db:
        condition: service_healthy
    restart: no
    networks:
      - reportify_network

volumes:
  pg_auth_data:

networks:
  reportify_network:
    external: true
