// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/ummuys/reportify/services/report/internal/dto"
)

// NewMockDatasourceDB creates a new instance of MockDatasourceDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatasourceDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatasourceDB {
	mock := &MockDatasourceDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatasourceDB is an autogenerated mock type for the DatasourceDB type
type MockDatasourceDB struct {
	mock.Mock
}

type MockDatasourceDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatasourceDB) EXPECT() *MockDatasourceDB_Expecter {
	return &MockDatasourceDB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDatasourceDB
func (_mock *MockDatasourceDB) Close() {
	_mock.Called()
	return
}

// MockDatasourceDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDatasourceDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDatasourceDB_Expecter) Close() *MockDatasourceDB_Close_Call {
	return &MockDatasourceDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDatasourceDB_Close_Call) Run(run func()) *MockDatasourceDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatasourceDB_Close_Call) Return() *MockDatasourceDB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDatasourceDB_Close_Call) RunAndReturn(run func()) *MockDatasourceDB_Close_Call {
	_c.Run(run)
	return _c
}

// ListColumns provides a mock function for the type MockDatasourceDB
func (_mock *MockDatasourceDB) ListColumns(ctx context.Context, in dto.ListColumnsParams) (dto.ListColumnsResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ListColumns")
	}

	var r0 dto.ListColumnsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListColumnsParams) (dto.ListColumnsResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListColumnsParams) dto.ListColumnsResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.ListColumnsResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ListColumnsParams) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasourceDB_ListColumns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListColumns'
type MockDatasourceDB_ListColumns_Call struct {
	*mock.Call
}

// ListColumns is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.ListColumnsParams
func (_e *MockDatasourceDB_Expecter) ListColumns(ctx interface{}, in interface{}) *MockDatasourceDB_ListColumns_Call {
	return &MockDatasourceDB_ListColumns_Call{Call: _e.mock.On("ListColumns", ctx, in)}
}

func (_c *MockDatasourceDB_ListColumns_Call) Run(run func(ctx context.Context, in dto.ListColumnsParams)) *MockDatasourceDB_ListColumns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ListColumnsParams
		if args[1] != nil {
			arg1 = args[1].(dto.ListColumnsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatasourceDB_ListColumns_Call) Return(listColumnsResult dto.ListColumnsResult, err error) *MockDatasourceDB_ListColumns_Call {
	_c.Call.Return(listColumnsResult, err)
	return _c
}

func (_c *MockDatasourceDB_ListColumns_Call) RunAndReturn(run func(ctx context.Context, in dto.ListColumnsParams) (dto.ListColumnsResult, error)) *MockDatasourceDB_ListColumns_Call {
	_c.Call.Return(run)
	return _c
}

// ListSchemas provides a mock function for the type MockDatasourceDB
func (_mock *MockDatasourceDB) ListSchemas(ctx context.Context) (dto.ListSchemasResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSchemas")
	}

	var r0 dto.ListSchemasResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (dto.ListSchemasResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) dto.ListSchemasResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(dto.ListSchemasResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasourceDB_ListSchemas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSchemas'
type MockDatasourceDB_ListSchemas_Call struct {
	*mock.Call
}

// ListSchemas is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatasourceDB_Expecter) ListSchemas(ctx interface{}) *MockDatasourceDB_ListSchemas_Call {
	return &MockDatasourceDB_ListSchemas_Call{Call: _e.mock.On("ListSchemas", ctx)}
}

func (_c *MockDatasourceDB_ListSchemas_Call) Run(run func(ctx context.Context)) *MockDatasourceDB_ListSchemas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatasourceDB_ListSchemas_Call) Return(listSchemasResult dto.ListSchemasResult, err error) *MockDatasourceDB_ListSchemas_Call {
	_c.Call.Return(listSchemasResult, err)
	return _c
}

func (_c *MockDatasourceDB_ListSchemas_Call) RunAndReturn(run func(ctx context.Context) (dto.ListSchemasResult, error)) *MockDatasourceDB_ListSchemas_Call {
	_c.Call.Return(run)
	return _c
}

// ListTables provides a mock function for the type MockDatasourceDB
func (_mock *MockDatasourceDB) ListTables(ctx context.Context, in dto.ListTablesParams) (dto.ListTablesResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ListTables")
	}

	var r0 dto.ListTablesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListTablesParams) (dto.ListTablesResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListTablesParams) dto.ListTablesResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.ListTablesResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ListTablesParams) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatasourceDB_ListTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTables'
type MockDatasourceDB_ListTables_Call struct {
	*mock.Call
}

// ListTables is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.ListTablesParams
func (_e *MockDatasourceDB_Expecter) ListTables(ctx interface{}, in interface{}) *MockDatasourceDB_ListTables_Call {
	return &MockDatasourceDB_ListTables_Call{Call: _e.mock.On("ListTables", ctx, in)}
}

func (_c *MockDatasourceDB_ListTables_Call) Run(run func(ctx context.Context, in dto.ListTablesParams)) *MockDatasourceDB_ListTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ListTablesParams
		if args[1] != nil {
			arg1 = args[1].(dto.ListTablesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatasourceDB_ListTables_Call) Return(listTablesResult dto.ListTablesResult, err error) *MockDatasourceDB_ListTables_Call {
	_c.Call.Return(listTablesResult, err)
	return _c
}

func (_c *MockDatasourceDB_ListTables_Call) RunAndReturn(run func(ctx context.Context, in dto.ListTablesParams) (dto.ListTablesResult, error)) *MockDatasourceDB_ListTables_Call {
	_c.Call.Return(run)
	return _c
}
