// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/ummuys/reportify/services/report/internal/dto"
)

// NewMockReportDB creates a new instance of MockReportDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportDB {
	mock := &MockReportDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReportDB is an autogenerated mock type for the ReportDB type
type MockReportDB struct {
	mock.Mock
}

type MockReportDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportDB) EXPECT() *MockReportDB_Expecter {
	return &MockReportDB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockReportDB
func (_mock *MockReportDB) Close() {
	_mock.Called()
	return
}

// MockReportDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReportDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockReportDB_Expecter) Close() *MockReportDB_Close_Call {
	return &MockReportDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockReportDB_Close_Call) Run(run func()) *MockReportDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReportDB_Close_Call) Return() *MockReportDB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReportDB_Close_Call) RunAndReturn(run func()) *MockReportDB_Close_Call {
	_c.Run(run)
	return _c
}

// CreateReport provides a mock function for the type MockReportDB
func (_mock *MockReportDB) CreateReport(ctx context.Context, in dto.CreateReportParams) (dto.CreateReportResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateReport")
	}

	var r0 dto.CreateReportResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateReportParams) (dto.CreateReportResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateReportParams) dto.CreateReportResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.CreateReportResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateReportParams) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDB_CreateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReport'
type MockReportDB_CreateReport_Call struct {
	*mock.Call
}

// CreateReport is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.CreateReportParams
func (_e *MockReportDB_Expecter) CreateReport(ctx interface{}, in interface{}) *MockReportDB_CreateReport_Call {
	return &MockReportDB_CreateReport_Call{Call: _e.mock.On("CreateReport", ctx, in)}
}

func (_c *MockReportDB_CreateReport_Call) Run(run func(ctx context.Context, in dto.CreateReportParams)) *MockReportDB_CreateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateReportParams
		if args[1] != nil {
			arg1 = args[1].(dto.CreateReportParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportDB_CreateReport_Call) Return(createReportResult dto.CreateReportResult, err error) *MockReportDB_CreateReport_Call {
	_c.Call.Return(createReportResult, err)
	return _c
}

func (_c *MockReportDB_CreateReport_Call) RunAndReturn(run func(ctx context.Context, in dto.CreateReportParams) (dto.CreateReportResult, error)) *MockReportDB_CreateReport_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReport provides a mock function for the type MockReportDB
func (_mock *MockReportDB) DeleteReport(ctx context.Context, in dto.DeleteReportParams) (dto.DeleteReportResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReport")
	}

	var r0 dto.DeleteReportResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.DeleteReportParams) (dto.DeleteReportResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.DeleteReportParams) dto.DeleteReportResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.DeleteReportResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.DeleteReportParams) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDB_DeleteReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReport'
type MockReportDB_DeleteReport_Call struct {
	*mock.Call
}

// DeleteReport is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.DeleteReportParams
func (_e *MockReportDB_Expecter) DeleteReport(ctx interface{}, in interface{}) *MockReportDB_DeleteReport_Call {
	return &MockReportDB_DeleteReport_Call{Call: _e.mock.On("DeleteReport", ctx, in)}
}

func (_c *MockReportDB_DeleteReport_Call) Run(run func(ctx context.Context, in dto.DeleteReportParams)) *MockReportDB_DeleteReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.DeleteReportParams
		if args[1] != nil {
			arg1 = args[1].(dto.DeleteReportParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportDB_DeleteReport_Call) Return(deleteReportResult dto.DeleteReportResult, err error) *MockReportDB_DeleteReport_Call {
	_c.Call.Return(deleteReportResult, err)
	return _c
}

func (_c *MockReportDB_DeleteReport_Call) RunAndReturn(run func(ctx context.Context, in dto.DeleteReportParams) (dto.DeleteReportResult, error)) *MockReportDB_DeleteReport_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReports provides a mock function for the type MockReportDB
func (_mock *MockReportDB) DeleteReports(ctx context.Context, in dto.DeleteReportsParams) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReports")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.DeleteReportsParams) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReportDB_DeleteReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReports'
type MockReportDB_DeleteReports_Call struct {
	*mock.Call
}

// DeleteReports is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.DeleteReportsParams
func (_e *MockReportDB_Expecter) DeleteReports(ctx interface{}, in interface{}) *MockReportDB_DeleteReports_Call {
	return &MockReportDB_DeleteReports_Call{Call: _e.mock.On("DeleteReports", ctx, in)}
}

func (_c *MockReportDB_DeleteReports_Call) Run(run func(ctx context.Context, in dto.DeleteReportsParams)) *MockReportDB_DeleteReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.DeleteReportsParams
		if args[1] != nil {
			arg1 = args[1].(dto.DeleteReportsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportDB_DeleteReports_Call) Return(err error) *MockReportDB_DeleteReports_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReportDB_DeleteReports_Call) RunAndReturn(run func(ctx context.Context, in dto.DeleteReportsParams) error) *MockReportDB_DeleteReports_Call {
	_c.Call.Return(run)
	return _c
}

// ListReports provides a mock function for the type MockReportDB
func (_mock *MockReportDB) ListReports(ctx context.Context, in dto.ListReportsParams) (dto.ListReportsResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ListReports")
	}

	var r0 dto.ListReportsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListReportsParams) (dto.ListReportsResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ListReportsParams) dto.ListReportsResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.ListReportsResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ListReportsParams) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDB_ListReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReports'
type MockReportDB_ListReports_Call struct {
	*mock.Call
}

// ListReports is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.ListReportsParams
func (_e *MockReportDB_Expecter) ListReports(ctx interface{}, in interface{}) *MockReportDB_ListReports_Call {
	return &MockReportDB_ListReports_Call{Call: _e.mock.On("ListReports", ctx, in)}
}

func (_c *MockReportDB_ListReports_Call) Run(run func(ctx context.Context, in dto.ListReportsParams)) *MockReportDB_ListReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ListReportsParams
		if args[1] != nil {
			arg1 = args[1].(dto.ListReportsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportDB_ListReports_Call) Return(listReportsResult dto.ListReportsResult, err error) *MockReportDB_ListReports_Call {
	_c.Call.Return(listReportsResult, err)
	return _c
}

func (_c *MockReportDB_ListReports_Call) RunAndReturn(run func(ctx context.Context, in dto.ListReportsParams) (dto.ListReportsResult, error)) *MockReportDB_ListReports_Call {
	_c.Call.Return(run)
	return _c
}

// ReportInfo provides a mock function for the type MockReportDB
func (_mock *MockReportDB) ReportInfo(ctx context.Context, in dto.ReportInfoParams) (dto.ReportInfoResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ReportInfo")
	}

	var r0 dto.ReportInfoResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ReportInfoParams) (dto.ReportInfoResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ReportInfoParams) dto.ReportInfoResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.ReportInfoResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ReportInfoParams) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDB_ReportInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportInfo'
type MockReportDB_ReportInfo_Call struct {
	*mock.Call
}

// ReportInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.ReportInfoParams
func (_e *MockReportDB_Expecter) ReportInfo(ctx interface{}, in interface{}) *MockReportDB_ReportInfo_Call {
	return &MockReportDB_ReportInfo_Call{Call: _e.mock.On("ReportInfo", ctx, in)}
}

func (_c *MockReportDB_ReportInfo_Call) Run(run func(ctx context.Context, in dto.ReportInfoParams)) *MockReportDB_ReportInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ReportInfoParams
		if args[1] != nil {
			arg1 = args[1].(dto.ReportInfoParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportDB_ReportInfo_Call) Return(reportInfoResult dto.ReportInfoResult, err error) *MockReportDB_ReportInfo_Call {
	_c.Call.Return(reportInfoResult, err)
	return _c
}

func (_c *MockReportDB_ReportInfo_Call) RunAndReturn(run func(ctx context.Context, in dto.ReportInfoParams) (dto.ReportInfoResult, error)) *MockReportDB_ReportInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ReportStatus provides a mock function for the type MockReportDB
func (_mock *MockReportDB) ReportStatus(ctx context.Context, in dto.ReportStatusParams) (dto.ReportStatusResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ReportStatus")
	}

	var r0 dto.ReportStatusResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ReportStatusParams) (dto.ReportStatusResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.ReportStatusParams) dto.ReportStatusResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.ReportStatusResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.ReportStatusParams) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDB_ReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportStatus'
type MockReportDB_ReportStatus_Call struct {
	*mock.Call
}

// ReportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.ReportStatusParams
func (_e *MockReportDB_Expecter) ReportStatus(ctx interface{}, in interface{}) *MockReportDB_ReportStatus_Call {
	return &MockReportDB_ReportStatus_Call{Call: _e.mock.On("ReportStatus", ctx, in)}
}

func (_c *MockReportDB_ReportStatus_Call) Run(run func(ctx context.Context, in dto.ReportStatusParams)) *MockReportDB_ReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.ReportStatusParams
		if args[1] != nil {
			arg1 = args[1].(dto.ReportStatusParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportDB_ReportStatus_Call) Return(reportStatusResult dto.ReportStatusResult, err error) *MockReportDB_ReportStatus_Call {
	_c.Call.Return(reportStatusResult, err)
	return _c
}

func (_c *MockReportDB_ReportStatus_Call) RunAndReturn(run func(ctx context.Context, in dto.ReportStatusParams) (dto.ReportStatusResult, error)) *MockReportDB_ReportStatus_Call {
	_c.Call.Return(run)
	return _c
}
