// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReportCache is an autogenerated mock type for the ReportCache type
type MockReportCache struct {
	mock.Mock
}

type MockReportCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportCache) EXPECT() *MockReportCache_Expecter {
	return &MockReportCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, keys
func (_m *MockReportCache) Delete(ctx context.Context, keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockReportCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockReportCache_Expecter) Delete(ctx interface{}, keys ...interface{}) *MockReportCache_Delete_Call {
	return &MockReportCache_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockReportCache_Delete_Call) Run(run func(ctx context.Context, keys ...string)) *MockReportCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockReportCache_Delete_Call) Return(_a0 error) *MockReportCache_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportCache_Delete_Call) RunAndReturn(run func(context.Context, ...string) error) *MockReportCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockReportCache) Get(ctx context.Context, key string) (*string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockReportCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockReportCache_Expecter) Get(ctx interface{}, key interface{}) *MockReportCache_Get_Call {
	return &MockReportCache_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockReportCache_Get_Call) Run(run func(ctx context.Context, key string)) *MockReportCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReportCache_Get_Call) Return(_a0 *string, _a1 error) *MockReportCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportCache_Get_Call) RunAndReturn(run func(context.Context, string) (*string, error)) *MockReportCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value
func (_m *MockReportCache) Set(ctx context.Context, key string, value string) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockReportCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockReportCache_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockReportCache_Set_Call {
	return &MockReportCache_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockReportCache_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockReportCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockReportCache_Set_Call) Return(_a0 error) *MockReportCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportCache_Set_Call) RunAndReturn(run func(context.Context, string, string) error) *MockReportCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportCache creates a new instance of MockReportCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportCache {
	mock := &MockReportCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
