// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/ummuys/reportify/services/report/internal/dto"
)

// MockReportDB is an autogenerated mock type for the ReportDB type
type MockReportDB struct {
	mock.Mock
}

type MockReportDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportDB) EXPECT() *MockReportDB_Expecter {
	return &MockReportDB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockReportDB) Close() {
	_m.Called()
}

// MockReportDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReportDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockReportDB_Expecter) Close() *MockReportDB_Close_Call {
	return &MockReportDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockReportDB_Close_Call) Run(run func()) *MockReportDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReportDB_Close_Call) Return() *MockReportDB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReportDB_Close_Call) RunAndReturn(run func()) *MockReportDB_Close_Call {
	_c.Run(run)
	return _c
}

// CreateReport provides a mock function with given fields: ctx, in
func (_m *MockReportDB) CreateReport(ctx context.Context, in dto.CreateReportParams) (dto.CreateReportResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateReport")
	}

	var r0 dto.CreateReportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateReportParams) (dto.CreateReportResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateReportParams) dto.CreateReportResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.CreateReportResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateReportParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportDB_CreateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReport'
type MockReportDB_CreateReport_Call struct {
	*mock.Call
}

// CreateReport is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.CreateReportParams
func (_e *MockReportDB_Expecter) CreateReport(ctx interface{}, in interface{}) *MockReportDB_CreateReport_Call {
	return &MockReportDB_CreateReport_Call{Call: _e.mock.On("CreateReport", ctx, in)}
}

func (_c *MockReportDB_CreateReport_Call) Run(run func(ctx context.Context, in dto.CreateReportParams)) *MockReportDB_CreateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateReportParams))
	})
	return _c
}

func (_c *MockReportDB_CreateReport_Call) Return(_a0 dto.CreateReportResult, _a1 error) *MockReportDB_CreateReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportDB_CreateReport_Call) RunAndReturn(run func(context.Context, dto.CreateReportParams) (dto.CreateReportResult, error)) *MockReportDB_CreateReport_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReport provides a mock function with given fields: ctx, in
func (_m *MockReportDB) DeleteReport(ctx context.Context, in dto.DeleteReportParams) (dto.DeleteReportResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReport")
	}

	var r0 dto.DeleteReportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.DeleteReportParams) (dto.DeleteReportResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.DeleteReportParams) dto.DeleteReportResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.DeleteReportResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.DeleteReportParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportDB_DeleteReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReport'
type MockReportDB_DeleteReport_Call struct {
	*mock.Call
}

// DeleteReport is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.DeleteReportParams
func (_e *MockReportDB_Expecter) DeleteReport(ctx interface{}, in interface{}) *MockReportDB_DeleteReport_Call {
	return &MockReportDB_DeleteReport_Call{Call: _e.mock.On("DeleteReport", ctx, in)}
}

func (_c *MockReportDB_DeleteReport_Call) Run(run func(ctx context.Context, in dto.DeleteReportParams)) *MockReportDB_DeleteReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.DeleteReportParams))
	})
	return _c
}

func (_c *MockReportDB_DeleteReport_Call) Return(_a0 dto.DeleteReportResult, _a1 error) *MockReportDB_DeleteReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportDB_DeleteReport_Call) RunAndReturn(run func(context.Context, dto.DeleteReportParams) (dto.DeleteReportResult, error)) *MockReportDB_DeleteReport_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReports provides a mock function with given fields: ctx, in
func (_m *MockReportDB) DeleteReports(ctx context.Context, in dto.DeleteReportsParams) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReports")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.DeleteReportsParams) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportDB_DeleteReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReports'
type MockReportDB_DeleteReports_Call struct {
	*mock.Call
}

// DeleteReports is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.DeleteReportsParams
func (_e *MockReportDB_Expecter) DeleteReports(ctx interface{}, in interface{}) *MockReportDB_DeleteReports_Call {
	return &MockReportDB_DeleteReports_Call{Call: _e.mock.On("DeleteReports", ctx, in)}
}

func (_c *MockReportDB_DeleteReports_Call) Run(run func(ctx context.Context, in dto.DeleteReportsParams)) *MockReportDB_DeleteReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.DeleteReportsParams))
	})
	return _c
}

func (_c *MockReportDB_DeleteReports_Call) Return(_a0 error) *MockReportDB_DeleteReports_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportDB_DeleteReports_Call) RunAndReturn(run func(context.Context, dto.DeleteReportsParams) error) *MockReportDB_DeleteReports_Call {
	_c.Call.Return(run)
	return _c
}

// ListReports provides a mock function with given fields: ctx, in
func (_m *MockReportDB) ListReports(ctx context.Context, in dto.ListReportsParams) (dto.ListReportsResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ListReports")
	}

	var r0 dto.ListReportsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ListReportsParams) (dto.ListReportsResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ListReportsParams) dto.ListReportsResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.ListReportsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ListReportsParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportDB_ListReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReports'
type MockReportDB_ListReports_Call struct {
	*mock.Call
}

// ListReports is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.ListReportsParams
func (_e *MockReportDB_Expecter) ListReports(ctx interface{}, in interface{}) *MockReportDB_ListReports_Call {
	return &MockReportDB_ListReports_Call{Call: _e.mock.On("ListReports", ctx, in)}
}

func (_c *MockReportDB_ListReports_Call) Run(run func(ctx context.Context, in dto.ListReportsParams)) *MockReportDB_ListReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.ListReportsParams))
	})
	return _c
}

func (_c *MockReportDB_ListReports_Call) Return(_a0 dto.ListReportsResult, _a1 error) *MockReportDB_ListReports_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportDB_ListReports_Call) RunAndReturn(run func(context.Context, dto.ListReportsParams) (dto.ListReportsResult, error)) *MockReportDB_ListReports_Call {
	_c.Call.Return(run)
	return _c
}

// RecreateReport provides a mock function with given fields: ctx, in
func (_m *MockReportDB) RecreateReport(ctx context.Context, in dto.RecreateReportParams) (dto.RecreateReportResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for RecreateReport")
	}

	var r0 dto.RecreateReportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RecreateReportParams) (dto.RecreateReportResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RecreateReportParams) dto.RecreateReportResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.RecreateReportResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RecreateReportParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportDB_RecreateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecreateReport'
type MockReportDB_RecreateReport_Call struct {
	*mock.Call
}

// RecreateReport is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.RecreateReportParams
func (_e *MockReportDB_Expecter) RecreateReport(ctx interface{}, in interface{}) *MockReportDB_RecreateReport_Call {
	return &MockReportDB_RecreateReport_Call{Call: _e.mock.On("RecreateReport", ctx, in)}
}

func (_c *MockReportDB_RecreateReport_Call) Run(run func(ctx context.Context, in dto.RecreateReportParams)) *MockReportDB_RecreateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.RecreateReportParams))
	})
	return _c
}

func (_c *MockReportDB_RecreateReport_Call) Return(_a0 dto.RecreateReportResult, _a1 error) *MockReportDB_RecreateReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportDB_RecreateReport_Call) RunAndReturn(run func(context.Context, dto.RecreateReportParams) (dto.RecreateReportResult, error)) *MockReportDB_RecreateReport_Call {
	_c.Call.Return(run)
	return _c
}

// ReportInfo provides a mock function with given fields: ctx, in
func (_m *MockReportDB) ReportInfo(ctx context.Context, in dto.ReportInfoParams) (dto.ReportInfoResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ReportInfo")
	}

	var r0 dto.ReportInfoResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportInfoParams) (dto.ReportInfoResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportInfoParams) dto.ReportInfoResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.ReportInfoResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportInfoParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportDB_ReportInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportInfo'
type MockReportDB_ReportInfo_Call struct {
	*mock.Call
}

// ReportInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.ReportInfoParams
func (_e *MockReportDB_Expecter) ReportInfo(ctx interface{}, in interface{}) *MockReportDB_ReportInfo_Call {
	return &MockReportDB_ReportInfo_Call{Call: _e.mock.On("ReportInfo", ctx, in)}
}

func (_c *MockReportDB_ReportInfo_Call) Run(run func(ctx context.Context, in dto.ReportInfoParams)) *MockReportDB_ReportInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.ReportInfoParams))
	})
	return _c
}

func (_c *MockReportDB_ReportInfo_Call) Return(_a0 dto.ReportInfoResult, _a1 error) *MockReportDB_ReportInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportDB_ReportInfo_Call) RunAndReturn(run func(context.Context, dto.ReportInfoParams) (dto.ReportInfoResult, error)) *MockReportDB_ReportInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ReportStatus provides a mock function with given fields: ctx, in
func (_m *MockReportDB) ReportStatus(ctx context.Context, in dto.ReportStatusParams) (dto.ReportStatusResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ReportStatus")
	}

	var r0 dto.ReportStatusResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportStatusParams) (dto.ReportStatusResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReportStatusParams) dto.ReportStatusResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.ReportStatusResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ReportStatusParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportDB_ReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportStatus'
type MockReportDB_ReportStatus_Call struct {
	*mock.Call
}

// ReportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.ReportStatusParams
func (_e *MockReportDB_Expecter) ReportStatus(ctx interface{}, in interface{}) *MockReportDB_ReportStatus_Call {
	return &MockReportDB_ReportStatus_Call{Call: _e.mock.On("ReportStatus", ctx, in)}
}

func (_c *MockReportDB_ReportStatus_Call) Run(run func(ctx context.Context, in dto.ReportStatusParams)) *MockReportDB_ReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.ReportStatusParams))
	})
	return _c
}

func (_c *MockReportDB_ReportStatus_Call) Return(_a0 dto.ReportStatusResult, _a1 error) *MockReportDB_ReportStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportDB_ReportStatus_Call) RunAndReturn(run func(context.Context, dto.ReportStatusParams) (dto.ReportStatusResult, error)) *MockReportDB_ReportStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportDB creates a new instance of MockReportDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportDB {
	mock := &MockReportDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
