// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: report/v1/report.proto

package reportv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReportAuthorId string                 `protobuf:"bytes,1,opt,name=report_author_id,json=reportAuthorId,proto3" json:"report_author_id,omitempty"`
	ReportName     string                 `protobuf:"bytes,2,opt,name=report_name,json=reportName,proto3" json:"report_name,omitempty"`
	ReportComm     string                 `protobuf:"bytes,3,opt,name=report_comm,json=reportComm,proto3" json:"report_comm,omitempty"`
	Query          string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	CsvSep         string                 `protobuf:"bytes,5,opt,name=csv_sep,json=csvSep,proto3" json:"csv_sep,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateReportRequest) Reset() {
	*x = CreateReportRequest{}
	mi := &file_report_v1_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportRequest) ProtoMessage() {}

func (x *CreateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportRequest.ProtoReflect.Descriptor instead.
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReportRequest) GetReportAuthorId() string {
	if x != nil {
		return x.ReportAuthorId
	}
	return ""
}

func (x *CreateReportRequest) GetReportName() string {
	if x != nil {
		return x.ReportName
	}
	return ""
}

func (x *CreateReportRequest) GetReportComm() string {
	if x != nil {
		return x.ReportComm
	}
	return ""
}

func (x *CreateReportRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CreateReportRequest) GetCsvSep() string {
	if x != nil {
		return x.CsvSep
	}
	return ""
}

type CreateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report_UUID   string                 `protobuf:"bytes,1,opt,name=report_UUID,json=reportUUID,proto3" json:"report_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReportResponse) Reset() {
	*x = CreateReportResponse{}
	mi := &file_report_v1_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReportResponse) ProtoMessage() {}

func (x *CreateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReportResponse.ProtoReflect.Descriptor instead.
func (*CreateReportResponse) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReportResponse) GetReport_UUID() string {
	if x != nil {
		return x.Report_UUID
	}
	return ""
}

type CheckReportStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportUuid    string                 `protobuf:"bytes,1,opt,name=report_uuid,json=reportUuid,proto3" json:"report_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReportStatusRequest) Reset() {
	*x = CheckReportStatusRequest{}
	mi := &file_report_v1_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReportStatusRequest) ProtoMessage() {}

func (x *CheckReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReportStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{2}
}

func (x *CheckReportStatusRequest) GetReportUuid() string {
	if x != nil {
		return x.ReportUuid
	}
	return ""
}

type CheckReportStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportStatus  string                 `protobuf:"bytes,1,opt,name=report_status,json=reportStatus,proto3" json:"report_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReportStatusResponse) Reset() {
	*x = CheckReportStatusResponse{}
	mi := &file_report_v1_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReportStatusResponse) ProtoMessage() {}

func (x *CheckReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_v1_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReportStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_report_v1_report_proto_rawDescGZIP(), []int{3}
}

func (x *CheckReportStatusResponse) GetReportStatus() string {
	if x != nil {
		return x.ReportStatus
	}
	return ""
}

var File_report_v1_report_proto protoreflect.FileDescriptor

const file_report_v1_report_proto_rawDesc = "" +
	"\n" +
	"\x16report/v1/report.proto\x12\treport.v1\"\xb0\x01\n" +
	"\x13CreateReportRequest\x12(\n" +
	"\x10report_author_id\x18\x01 \x01(\tR\x0ereportAuthorId\x12\x1f\n" +
	"\vreport_name\x18\x02 \x01(\tR\n" +
	"reportName\x12\x1f\n" +
	"\vreport_comm\x18\x03 \x01(\tR\n" +
	"reportComm\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x17\n" +
	"\acsv_sep\x18\x05 \x01(\tR\x06csvSep\"7\n" +
	"\x14CreateReportResponse\x12\x1f\n" +
	"\vreport_UUID\x18\x01 \x01(\tR\n" +
	"reportUUID\";\n" +
	"\x18CheckReportStatusRequest\x12\x1f\n" +
	"\vreport_uuid\x18\x01 \x01(\tR\n" +
	"reportUuid\"@\n" +
	"\x19CheckReportStatusResponse\x12#\n" +
	"\rreport_status\x18\x01 \x01(\tR\freportStatus2\xc0\x01\n" +
	"\rReportService\x12O\n" +
	"\fCreateReport\x12\x1e.report.v1.CreateReportRequest\x1a\x1f.report.v1.CreateReportResponse\x12^\n" +
	"\x11CheckReportStatus\x12#.report.v1.CheckReportStatusRequest\x1a$.report.v1.CheckReportStatusResponseB7Z5github.com/ummuys/reportify/api/pb/report/v1;reportv1b\x06proto3"

var (
	file_report_v1_report_proto_rawDescOnce sync.Once
	file_report_v1_report_proto_rawDescData []byte
)

func file_report_v1_report_proto_rawDescGZIP() []byte {
	file_report_v1_report_proto_rawDescOnce.Do(func() {
		file_report_v1_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_v1_report_proto_rawDesc), len(file_report_v1_report_proto_rawDesc)))
	})
	return file_report_v1_report_proto_rawDescData
}

var file_report_v1_report_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_report_v1_report_proto_goTypes = []any{
	(*CreateReportRequest)(nil),       // 0: report.v1.CreateReportRequest
	(*CreateReportResponse)(nil),      // 1: report.v1.CreateReportResponse
	(*CheckReportStatusRequest)(nil),  // 2: report.v1.CheckReportStatusRequest
	(*CheckReportStatusResponse)(nil), // 3: report.v1.CheckReportStatusResponse
}
var file_report_v1_report_proto_depIdxs = []int32{
	0, // 0: report.v1.ReportService.CreateReport:input_type -> report.v1.CreateReportRequest
	2, // 1: report.v1.ReportService.CheckReportStatus:input_type -> report.v1.CheckReportStatusRequest
	1, // 2: report.v1.ReportService.CreateReport:output_type -> report.v1.CreateReportResponse
	3, // 3: report.v1.ReportService.CheckReportStatus:output_type -> report.v1.CheckReportStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_report_v1_report_proto_init() }
func file_report_v1_report_proto_init() {
	if File_report_v1_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_v1_report_proto_rawDesc), len(file_report_v1_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_v1_report_proto_goTypes,
		DependencyIndexes: file_report_v1_report_proto_depIdxs,
		MessageInfos:      file_report_v1_report_proto_msgTypes,
	}.Build()
	File_report_v1_report_proto = out.File
	file_report_v1_report_proto_goTypes = nil
	file_report_v1_report_proto_depIdxs = nil
}
