// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: report/cache/v1/report_cache.proto

package rcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_report_cache_v1_report_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_report_cache_v1_report_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_report_cache_v1_report_cache_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_report_cache_v1_report_cache_proto_rawDescGZIP(), []int{3}
}

type DeleteAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllRequest) Reset() {
	*x = DeleteAllRequest{}
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllRequest) ProtoMessage() {}

func (x *DeleteAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllRequest.ProtoReflect.Descriptor instead.
func (*DeleteAllRequest) Descriptor() ([]byte, []int) {
	return file_report_cache_v1_report_cache_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAllRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllResponse) Reset() {
	*x = DeleteAllResponse{}
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllResponse) ProtoMessage() {}

func (x *DeleteAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_cache_v1_report_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllResponse.ProtoReflect.Descriptor instead.
func (*DeleteAllResponse) Descriptor() ([]byte, []int) {
	return file_report_cache_v1_report_cache_proto_rawDescGZIP(), []int{5}
}

var File_report_cache_v1_report_cache_proto protoreflect.FileDescriptor

const file_report_cache_v1_report_cache_proto_rawDesc = "" +
	"\n" +
	"\"report/cache/v1/report_cache.proto\x12\x0freport.cache.v1\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"%\n" +
	"\vGetResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"7\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x10\n" +
	"\x0eDeleteResponse\"$\n" +
	"\x10DeleteAllRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x13\n" +
	"\x11DeleteAllResponse2\xf5\x01\n" +
	"\x12ReportCacheService\x12@\n" +
	"\x03Get\x12\x1b.report.cache.v1.GetRequest\x1a\x1c.report.cache.v1.GetResponse\x12I\n" +
	"\x06Delete\x12\x1e.report.cache.v1.DeleteRequest\x1a\x1f.report.cache.v1.DeleteResponse\x12R\n" +
	"\tDeleteAll\x12!.report.cache.v1.DeleteAllRequest\x1a\".report.cache.v1.DeleteAllResponseB9Z7github.com/ummuys/reportify/api/pb/report/cache/v1;rcv1b\x06proto3"

var (
	file_report_cache_v1_report_cache_proto_rawDescOnce sync.Once
	file_report_cache_v1_report_cache_proto_rawDescData []byte
)

func file_report_cache_v1_report_cache_proto_rawDescGZIP() []byte {
	file_report_cache_v1_report_cache_proto_rawDescOnce.Do(func() {
		file_report_cache_v1_report_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_cache_v1_report_cache_proto_rawDesc), len(file_report_cache_v1_report_cache_proto_rawDesc)))
	})
	return file_report_cache_v1_report_cache_proto_rawDescData
}

var file_report_cache_v1_report_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_report_cache_v1_report_cache_proto_goTypes = []any{
	(*GetRequest)(nil),        // 0: report.cache.v1.GetRequest
	(*GetResponse)(nil),       // 1: report.cache.v1.GetResponse
	(*DeleteRequest)(nil),     // 2: report.cache.v1.DeleteRequest
	(*DeleteResponse)(nil),    // 3: report.cache.v1.DeleteResponse
	(*DeleteAllRequest)(nil),  // 4: report.cache.v1.DeleteAllRequest
	(*DeleteAllResponse)(nil), // 5: report.cache.v1.DeleteAllResponse
}
var file_report_cache_v1_report_cache_proto_depIdxs = []int32{
	0, // 0: report.cache.v1.ReportCacheService.Get:input_type -> report.cache.v1.GetRequest
	2, // 1: report.cache.v1.ReportCacheService.Delete:input_type -> report.cache.v1.DeleteRequest
	4, // 2: report.cache.v1.ReportCacheService.DeleteAll:input_type -> report.cache.v1.DeleteAllRequest
	1, // 3: report.cache.v1.ReportCacheService.Get:output_type -> report.cache.v1.GetResponse
	3, // 4: report.cache.v1.ReportCacheService.Delete:output_type -> report.cache.v1.DeleteResponse
	5, // 5: report.cache.v1.ReportCacheService.DeleteAll:output_type -> report.cache.v1.DeleteAllResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_report_cache_v1_report_cache_proto_init() }
func file_report_cache_v1_report_cache_proto_init() {
	if File_report_cache_v1_report_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_cache_v1_report_cache_proto_rawDesc), len(file_report_cache_v1_report_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_cache_v1_report_cache_proto_goTypes,
		DependencyIndexes: file_report_cache_v1_report_cache_proto_depIdxs,
		MessageInfos:      file_report_cache_v1_report_cache_proto_msgTypes,
	}.Build()
	File_report_cache_v1_report_cache_proto = out.File
	file_report_cache_v1_report_cache_proto_goTypes = nil
	file_report_cache_v1_report_cache_proto_depIdxs = nil
}
