// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/ummuys/reportify/services/auth/internal/dto"
)

// MockAuthDB is an autogenerated mock type for the AuthDB type
type MockAuthDB struct {
	mock.Mock
}

type MockAuthDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthDB) EXPECT() *MockAuthDB_Expecter {
	return &MockAuthDB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockAuthDB) Close() {
	_m.Called()
}

// MockAuthDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockAuthDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockAuthDB_Expecter) Close() *MockAuthDB_Close_Call {
	return &MockAuthDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockAuthDB_Close_Call) Run(run func()) *MockAuthDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthDB_Close_Call) Return() *MockAuthDB_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthDB_Close_Call) RunAndReturn(run func()) *MockAuthDB_Close_Call {
	_c.Run(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, in
func (_m *MockAuthDB) CreateUser(ctx context.Context, in dto.CreateUserParams) (dto.CreateUserResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 dto.CreateUserResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserParams) (dto.CreateUserResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserParams) dto.CreateUserResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.CreateUserResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateUserParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthDB_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthDB_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.CreateUserParams
func (_e *MockAuthDB_Expecter) CreateUser(ctx interface{}, in interface{}) *MockAuthDB_CreateUser_Call {
	return &MockAuthDB_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, in)}
}

func (_c *MockAuthDB_CreateUser_Call) Run(run func(ctx context.Context, in dto.CreateUserParams)) *MockAuthDB_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateUserParams))
	})
	return _c
}

func (_c *MockAuthDB_CreateUser_Call) Return(_a0 dto.CreateUserResult, _a1 error) *MockAuthDB_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthDB_CreateUser_Call) RunAndReturn(run func(context.Context, dto.CreateUserParams) (dto.CreateUserResult, error)) *MockAuthDB_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, in
func (_m *MockAuthDB) DeleteUser(ctx context.Context, in dto.DeleteUserParams) (dto.DeleteUserResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 dto.DeleteUserResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.DeleteUserParams) (dto.DeleteUserResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.DeleteUserParams) dto.DeleteUserResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.DeleteUserResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.DeleteUserParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthDB_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockAuthDB_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.DeleteUserParams
func (_e *MockAuthDB_Expecter) DeleteUser(ctx interface{}, in interface{}) *MockAuthDB_DeleteUser_Call {
	return &MockAuthDB_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, in)}
}

func (_c *MockAuthDB_DeleteUser_Call) Run(run func(ctx context.Context, in dto.DeleteUserParams)) *MockAuthDB_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.DeleteUserParams))
	})
	return _c
}

func (_c *MockAuthDB_DeleteUser_Call) Return(_a0 dto.DeleteUserResult, _a1 error) *MockAuthDB_DeleteUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthDB_DeleteUser_Call) RunAndReturn(run func(context.Context, dto.DeleteUserParams) (dto.DeleteUserResult, error)) *MockAuthDB_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx
func (_m *MockAuthDB) ListUsers(ctx context.Context) (dto.ListUsersResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 dto.ListUsersResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (dto.ListUsersResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) dto.ListUsersResult); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(dto.ListUsersResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthDB_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockAuthDB_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthDB_Expecter) ListUsers(ctx interface{}) *MockAuthDB_ListUsers_Call {
	return &MockAuthDB_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx)}
}

func (_c *MockAuthDB_ListUsers_Call) Run(run func(ctx context.Context)) *MockAuthDB_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAuthDB_ListUsers_Call) Return(_a0 dto.ListUsersResult, _a1 error) *MockAuthDB_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthDB_ListUsers_Call) RunAndReturn(run func(context.Context) (dto.ListUsersResult, error)) *MockAuthDB_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, username
func (_m *MockAuthDB) Login(ctx context.Context, username string) (dto.AuthUser, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 dto.AuthUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dto.AuthUser, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.AuthUser); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(dto.AuthUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthDB_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthDB_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockAuthDB_Expecter) Login(ctx interface{}, username interface{}) *MockAuthDB_Login_Call {
	return &MockAuthDB_Login_Call{Call: _e.mock.On("Login", ctx, username)}
}

func (_c *MockAuthDB_Login_Call) Run(run func(ctx context.Context, username string)) *MockAuthDB_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthDB_Login_Call) Return(_a0 dto.AuthUser, _a1 error) *MockAuthDB_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthDB_Login_Call) RunAndReturn(run func(context.Context, string) (dto.AuthUser, error)) *MockAuthDB_Login_Call {
	_c.Call.Return(run)
	return _c
}

// SetAdminUUID provides a mock function with given fields: UUID
func (_m *MockAuthDB) SetAdminUUID(UUID string) {
	_m.Called(UUID)
}

// MockAuthDB_SetAdminUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAdminUUID'
type MockAuthDB_SetAdminUUID_Call struct {
	*mock.Call
}

// SetAdminUUID is a helper method to define mock.On call
//   - UUID string
func (_e *MockAuthDB_Expecter) SetAdminUUID(UUID interface{}) *MockAuthDB_SetAdminUUID_Call {
	return &MockAuthDB_SetAdminUUID_Call{Call: _e.mock.On("SetAdminUUID", UUID)}
}

func (_c *MockAuthDB_SetAdminUUID_Call) Run(run func(UUID string)) *MockAuthDB_SetAdminUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthDB_SetAdminUUID_Call) Return() *MockAuthDB_SetAdminUUID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthDB_SetAdminUUID_Call) RunAndReturn(run func(string)) *MockAuthDB_SetAdminUUID_Call {
	_c.Run(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, in
func (_m *MockAuthDB) UpdateUser(ctx context.Context, in dto.UpdateUserParams) (dto.UpdateUserResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 dto.UpdateUserResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateUserParams) (dto.UpdateUserResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateUserParams) dto.UpdateUserResult); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(dto.UpdateUserResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdateUserParams) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthDB_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockAuthDB_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.UpdateUserParams
func (_e *MockAuthDB_Expecter) UpdateUser(ctx interface{}, in interface{}) *MockAuthDB_UpdateUser_Call {
	return &MockAuthDB_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, in)}
}

func (_c *MockAuthDB_UpdateUser_Call) Run(run func(ctx context.Context, in dto.UpdateUserParams)) *MockAuthDB_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.UpdateUserParams))
	})
	return _c
}

func (_c *MockAuthDB_UpdateUser_Call) Return(out dto.UpdateUserResult, err error) *MockAuthDB_UpdateUser_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *MockAuthDB_UpdateUser_Call) RunAndReturn(run func(context.Context, dto.UpdateUserParams) (dto.UpdateUserResult, error)) *MockAuthDB_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthDB creates a new instance of MockAuthDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthDB {
	mock := &MockAuthDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
