// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/ummuys/reportify/pkg/tm"
)

// NewMockTokenManager creates a new instance of MockTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenManager {
	mock := &MockTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenManager is an autogenerated mock type for the TokenManager type
type MockTokenManager struct {
	mock.Mock
}

type MockTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenManager) EXPECT() *MockTokenManager_Expecter {
	return &MockTokenManager_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) GenerateAccessToken(user_id string, role string) (string, error) {
	ret := _mock.Called(user_id, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(user_id, role)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(user_id, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(user_id, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenManager_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - user_id string
//   - role string
func (_e *MockTokenManager_Expecter) GenerateAccessToken(user_id interface{}, role interface{}) *MockTokenManager_GenerateAccessToken_Call {
	return &MockTokenManager_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", user_id, role)}
}

func (_c *MockTokenManager_GenerateAccessToken_Call) Run(run func(user_id string, role string)) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenManager_GenerateAccessToken_Call) Return(s string, err error) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenManager_GenerateAccessToken_Call) RunAndReturn(run func(user_id string, role string) (string, error)) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) GenerateRefreshToken(user_id string, role string) (string, error) {
	ret := _mock.Called(user_id, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(user_id, role)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(user_id, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(user_id, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenManager_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - user_id string
//   - role string
func (_e *MockTokenManager_Expecter) GenerateRefreshToken(user_id interface{}, role interface{}) *MockTokenManager_GenerateRefreshToken_Call {
	return &MockTokenManager_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", user_id, role)}
}

func (_c *MockTokenManager_GenerateRefreshToken_Call) Run(run func(user_id string, role string)) *MockTokenManager_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenManager_GenerateRefreshToken_Call) Return(s string, err error) *MockTokenManager_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenManager_GenerateRefreshToken_Call) RunAndReturn(run func(user_id string, role string) (string, error)) *MockTokenManager_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshLifetime provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) GetRefreshLifetime() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshLifetime")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockTokenManager_GetRefreshLifetime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshLifetime'
type MockTokenManager_GetRefreshLifetime_Call struct {
	*mock.Call
}

// GetRefreshLifetime is a helper method to define mock.On call
func (_e *MockTokenManager_Expecter) GetRefreshLifetime() *MockTokenManager_GetRefreshLifetime_Call {
	return &MockTokenManager_GetRefreshLifetime_Call{Call: _e.mock.On("GetRefreshLifetime")}
}

func (_c *MockTokenManager_GetRefreshLifetime_Call) Run(run func()) *MockTokenManager_GetRefreshLifetime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenManager_GetRefreshLifetime_Call) Return(duration time.Duration) *MockTokenManager_GetRefreshLifetime_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockTokenManager_GetRefreshLifetime_Call) RunAndReturn(run func() time.Duration) *MockTokenManager_GetRefreshLifetime_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) ValidateAccessToken(rawToken string) (pkg.AccessClaims, error) {
	ret := _mock.Called(rawToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 pkg.AccessClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (pkg.AccessClaims, error)); ok {
		return returnFunc(rawToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) pkg.AccessClaims); ok {
		r0 = returnFunc(rawToken)
	} else {
		r0 = ret.Get(0).(pkg.AccessClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(rawToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockTokenManager_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - rawToken string
func (_e *MockTokenManager_Expecter) ValidateAccessToken(rawToken interface{}) *MockTokenManager_ValidateAccessToken_Call {
	return &MockTokenManager_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", rawToken)}
}

func (_c *MockTokenManager_ValidateAccessToken_Call) Run(run func(rawToken string)) *MockTokenManager_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenManager_ValidateAccessToken_Call) Return(accessClaims pkg.AccessClaims, err error) *MockTokenManager_ValidateAccessToken_Call {
	_c.Call.Return(accessClaims, err)
	return _c
}

func (_c *MockTokenManager_ValidateAccessToken_Call) RunAndReturn(run func(rawToken string) (pkg.AccessClaims, error)) *MockTokenManager_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) ValidateRefreshToken(rawToken string) (pkg.RefreshClaims, error) {
	ret := _mock.Called(rawToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 pkg.RefreshClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (pkg.RefreshClaims, error)); ok {
		return returnFunc(rawToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) pkg.RefreshClaims); ok {
		r0 = returnFunc(rawToken)
	} else {
		r0 = ret.Get(0).(pkg.RefreshClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(rawToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockTokenManager_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - rawToken string
func (_e *MockTokenManager_Expecter) ValidateRefreshToken(rawToken interface{}) *MockTokenManager_ValidateRefreshToken_Call {
	return &MockTokenManager_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", rawToken)}
}

func (_c *MockTokenManager_ValidateRefreshToken_Call) Run(run func(rawToken string)) *MockTokenManager_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenManager_ValidateRefreshToken_Call) Return(refreshClaims pkg.RefreshClaims, err error) *MockTokenManager_ValidateRefreshToken_Call {
	_c.Call.Return(refreshClaims, err)
	return _c
}

func (_c *MockTokenManager_ValidateRefreshToken_Call) RunAndReturn(run func(rawToken string) (pkg.RefreshClaims, error)) *MockTokenManager_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
